@startuml

title __CLASS's Class Diagram__\n

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.Comments {
          + comment : String
          + date : String
          + time : String
          + username : String
          + Comments()
          + Comments()
          + getComment()
          + getDate()
          + getTime()
          + getUsername()
          + setComment()
          + setDate()
          + setTime()
          + setUsername()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.DateDialog {
          ~ txtDate : EditText
          + DateDialog()
          + onCreateDialog()
          + onDateSet()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.FindFriends {
          + fullname : String
          + profileimage : String
          + status : String
          + FindFriends()
          + FindFriends()
          + getFullname()
          + getProfileimage()
          + getStatus()
          + setFullname()
          + setProfileimage()
          + setStatus()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.Friends {
          + date : String
          + Friends()
          + Friends()
          + getDate()
          + setDate()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.Messages {
          + date : String
          + from : String
          + message : String
          + time : String
          + type : String
          + Messages()
          + Messages()
          + getDate()
          + getFrom()
          + getMessage()
          + getTime()
          + getType()
          + setDate()
          + setFrom()
          + setMessage()
          + setTime()
          + setType()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.MessagesAdapter {
          - mAuth : FirebaseAuth
          - userDatabaseRef : DatabaseReference
          - userMessagesList : List<Messages>
          + MessagesAdapter()
          + getItemCount()
          + onBindViewHolder()
          + onCreateViewHolder()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.MessagesAdapter.MessageViewHolder {
          + ReceiverMessageText : TextView
          + SenderMessageText : TextView
          + receiverProfileImage : CircleImageView
          + MessageViewHolder()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.Posts {
          + date : String
          + description : String
          + fullname : String
          + postimage : String
          + profileimage : String
          + time : String
          + uid : String
          + Posts()
          + Posts()
          + getDate()
          + getDescription()
          + getFullname()
          + getPostimage()
          + getProfileimage()
          + getTime()
          + getUid()
          + setDate()
          + setDescription()
          + setFullname()
          + setPostimage()
          + setProfileimage()
          + setTime()
          + setUid()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Class {
      class com.yukkajian4.ahmad.yukkajian.Class.Users {
          + fullname : String
          + Users()
          + Users()
          + getFullname()
          + setFullname()
      }
    }
  }
  

  com.yukkajian4.ahmad.yukkajian.Class.DateDialog .up.|> android.app.DatePickerDialog.OnDateSetListener
  com.yukkajian4.ahmad.yukkajian.Class.DateDialog -up-|> android.app.DialogFragment
  com.yukkajian4.ahmad.yukkajian.Class.MessagesAdapter +-down- com.yukkajian4.ahmad.yukkajian.Class.MessagesAdapter.MessageViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
