@startuml

title __MENU's Class Diagram__\n

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Menu {
      class com.yukkajian4.ahmad.yukkajian.Menu.FindFriendsActivity {
          - SearchButton : ImageButton
          - SearchInputText : EditText
          - SearchResultList : RecyclerView
          - allUsersDatabaseRef : DatabaseReference
          - mToolbar : Toolbar
          # onCreate()
          - SearchPeopleAndFriends()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Menu {
      class com.yukkajian4.ahmad.yukkajian.Menu.FindFriendsActivity.FindFriendsViewHolder {
          ~ mView : View
          + FindFriendsViewHolder()
          + setFullname()
          + setProfileimage()
          + setStatus()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Menu {
      class com.yukkajian4.ahmad.yukkajian.Menu.ProfileActivity {
          - currentUserId : String
          - mAuth : FirebaseAuth
          - profileUserRef : DatabaseReference
          - userCountry : TextView
          - userDOB : TextView
          - userGender : TextView
          - userName : TextView
          - userProfilName : TextView
          - userProfileImage : CircleImageView
          - userRelation : TextView
          - userStatus : TextView
          # onCreate()
      }
    }
  }
  

  namespace com.yukkajian4.ahmad.yukkajian {
    namespace Menu {
      class com.yukkajian4.ahmad.yukkajian.Menu.SettingsActivity {
          {static} ~ Gallery_Pick : int
          - PostUsersRef : DatabaseReference
          - SettingsUserRef : DatabaseReference
          - UpdateAccountSettingsButton : Button
          - UserProfileImageRef : StorageReference
          - currentuser : String
          - loadingBar : ProgressDialog
          - mAuth : FirebaseAuth
          - mToolbar : Toolbar
          - userCountry : EditText
          - userDOB : EditText
          - userGender : EditText
          - userName : EditText
          - userProfilName : EditText
          - userProfileImage : CircleImageView
          - userRelation : EditText
          - userStatus : EditText
          # onActivityResult()
          # onCreate()
          - SendUserToMainActivity()
          - UpdateAccountInfo()
          - ValidateAccountInfo()
      }
    }
  }
  

  com.yukkajian4.ahmad.yukkajian.Menu.FindFriendsActivity +-down- com.yukkajian4.ahmad.yukkajian.Menu.FindFriendsActivity.FindFriendsViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
